version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - sudo apt update
      - sudo apt install -y python3-pip
      - sudo apt install -y ros-humble-ros-base
      - sudo apt install -y ros-humble-colcon-common-extensions
      - sudo apt install -y python3-colcon-common-extensions
      - sudo apt install -y python3-rosdep
      - sudo rosdep init
      - rosdep update
      - rosdep install --from-paths . --ignore-src -r -y
      - source /opt/ros/humble/setup.bash
      - colcon build --continue-on-error
    post_build:
      - source install/setup.bash

python:

