# Default initial positions for ur3e_rg2's ros2_control fake system

initial_positions:
  ur3e_elbow_joint: 0
  ur3e_finger_width: 0
  ur3e_shoulder_lift_joint: 0
  ur3e_shoulder_pan_joint: 0
  ur3e_wrist_1_joint: 0
  ur3e_wrist_2_joint: 0
  ur3e_wrist_3_joint: 0